/**
 * @file timer.h
 *
 * @brief Timer constants
 *
 */
#ifndef TIMER_H
#define TIMER_H

#define TM_ZERO 0

#define TM_REWARDS_ELLIPSIS_PRINT_START 2
#define TM_REWARDS_ELLIPSIS_PRINT_END   16
#define TM_REWARD_DISPLAY_INTERVAL      15
#define TM_REWARD_INCREMENT_INTERVAL    20

#define TM_DISPLAY_REWARDS_CONT_WAIT (TM_REWARDS_ELLIPSIS_PRINT_END + TM_REWARD_DISPLAY_INTERVAL)
#define TM_HAND_REWARD_INCR_WAIT     (TM_DISPLAY_REWARDS_CONT_WAIT + TM_REWARD_DISPLAY_INTERVAL)

#define MENU_POP_OUT_ANIM_FRAMES 20

#endif // TIMER_H
